license          "Apache 2.0"
maintainer       "Mark Sonnabaum"
maintainer_email "mark.sonnabaum@acquia.com"
license          "Apache 2.0"
description      "Installs phpunit"
version          "0.9.1"
depends          "php"
recipe           "phpunit", "Installs phpunit unit testing suite"
